name: ocean_data_gateway
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - aiohttp
  - cf_xarray>=0.6
  - dask
  - erddapy
  - flake8
  - h5netcdf
  - importlib_resources
  - intake
  - intake-xarray
  #- ioos_qc
  - ipython
  - isort
  - joblib
  - jupyter
  - jupyterlab
  - matplotlib
  - pandas
  - pint
  - pint-pandas
  - pint-xarray
  - pytest
  - requests
  - scipy
  - xarray
  - pip
    # LC 2022-10-13: 2.0.1 release of ioos_qc doesn't have fix for xarray API
    # changes. We'll pip install it for the time being until a new release on
    # conda-forge is available.
  - pip:
    - git+https://github.com/ioos/ioos_qc@main#ioos_qc
