name: ocean_data_gateway
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - aiohttp
  - dask
  - erddapy
  - flake8
  - intake
  - intake-xarray
  - ioos_qc
  - ipython
  - isort
  - joblib
  - jupyter
  - jupyterlab
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pytest
  - requests
  - scipy
  - xarray
