name: ocean_data_gateway
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - jupyter
  - jupyterlab
  - numpy
  - scipy
  - dask
  - netcdf4
  - matplotlib
  - joblib
  - shapely
  - intake
  - pandas
  - xarray
  - requests
  - flake8
  - isort
  - erddapy
  - pytest
  - ipython
  - aiohttp
  - intake-xarray
