name: test_env_ocean_data_gateway
channels:
  - conda-forge
dependencies:
  - python=3.8
  ############## These will have to be adjusted to your specific project
  - jupyter
  - jupyterlab
  - numpy
  - scipy
  - dask
  - netcdf4
  - matplotlib
  - joblib
  - shapely
  - intake
  - pandas
  - xarray
  - requests
  - flake8
  - isort
  - erddapy
  - pytest
  - ipython
  - aiohttp
  - intake-xarray
  ##############
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
