name: ocean_data_gateway_docs
channels:
  - conda-forge
dependencies:
   - python=3.8
   # If your docs code examples depend on other packages add them here
   - jupyter
   - jupyterlab
   - numpy
   - scipy
   - dask
   - netcdf4
   - matplotlib
   - joblib
   - shapely
   - intake
   - pandas
   - xarray
   - requests
   - flake8
   - isort
   - erddapy
   - pytest
   - ipython
   - aiohttp
   - intake-xarray
   # These are needed for the docs themselves
   - numpydoc
   - sphinx
   - sphinx_rtd_theme
   - ipython
   - nbconvert
   - nbformat
   - ipykernel
   - pandoc
   - recommonmark
   - pip
   - pip:
     - git+https://github.com/axiom-data-science/ocean_data_gateway.git#egg=ocean_data_gateway
     - docrep<=0.2.7
     - nbsphinx
     - jupyter_client
     - sphinx_pangeo_theme
     - sphinx-copybutton
     - sphinxcontrib-srclinks
