name: ocean_data_gateway_docs
channels:
  - conda-forge
  - defaults
dependencies:
   - python=3.8
   # If your docs code examples depend on other packages add them here
   # But docs that are notebooks are not rerun in the doc-making process
   # so don't need all those packages
   # - cf_xarray
   # - ipython
   # - jupyter
   # - jupyterlab
   - ocean_data_gateway
   # These are needed for the docs themselves
   - numpydoc
   # https://stackoverflow.com/questions/68642540/nbsphinx-causes-build-to-fail-when-building-jupyter-notebooks
   - sphinx==4.0.2
   - sphinx_rtd_theme
   - ipython
   - nbconvert
   - nbformat
   - ipykernel
   - pandoc
   - recommonmark
   - pip
   - pip:
     - docrep<=0.2.7
     - nbsphinx
     - jupyter_client
     - sphinx_pangeo_theme
     - sphinx-copybutton
     - sphinxcontrib-srclinks
