name: ocean_data_gateway_docs
channels:
  - conda-forge
dependencies:
   - python=3.8
   # If your docs code examples depend on other packages add them here
   - aiohttp
   - cf_xarray>=0.6
   - dask
   - erddapy
   - flake8
   - h5netcdf
   - intake
   - intake-xarray
   - ioos_qc
   - ipython
   - isort
   - joblib
   - jupyter
   - jupyterlab
   - matplotlib
   - netcdf4
   - numpy
   - ocean_data_gateway
   - pandas
   - pint
   - pint-pandas
   - pint-xarray
   - pytest
   - requests
   - scipy
   - xarray
   # These are needed for the docs themselves
   - numpydoc
   # https://stackoverflow.com/questions/68642540/nbsphinx-causes-build-to-fail-when-building-jupyter-notebooks
   - sphinx==4.0.2
   - sphinx_rtd_theme
   - ipython
   - nbconvert
   - nbformat
   - ipykernel
   - pandoc
   - recommonmark
   - pip
   - pip:
     - docrep<=0.2.7
     - nbsphinx
     - jupyter_client
     - sphinx_pangeo_theme
     - sphinx-copybutton
     - sphinxcontrib-srclinks
